# 🛠️ Arcane Empires: Python Configuration
CONFIG = {
    "game": {
        "name": "Arcane Empires",
        "version": "1.0.0",
        "developer": "Cyberware Studios",
        "save_directory": "./saves/",
        "language": "en",
        "theme": "cyberpunk",
    },
    "graphics": {
        "resolution": "2560x1440",
        "fullscreen": True,
        "v_sync": True,
        "fps_limit": 120,
        "color_mode": "neon_glow",
        "ui_style": "holographic",
        "particle_effects": "high",
    },
    "physics": {
        "enable_ragdoll": True,
        "environmental_interaction": True,
        "gravity_strength": 9.8,
        "bullet_physics": "realistic",
    },
    "audio": {
        "master_volume": 80,
        "music_volume": 70,
        "sfx_volume": 85,
        "ambient_volume": 65,
        "dialogue_volume": 75,
        "mute": False,
        "dynamic_audio": True,
        "radio_stations": ["Cyberwave FM", "Underground Byte", "Hacktunes"],
    },
    "controls": {
        "move_up": "W",
        "move_down": "S",
        "move_left": "A",
        "move_right": "D",
        "action": "Space",
        "interact": "E",
        "menu": "Escape",
        "hack_mode": "Q",
        "scan_environment": "X",
        "quick_hack": "F",
    },
    "gameplay": {
        "difficulty": "Adaptive",
        "auto_save": True,
        "max_inventory_size": 100,
        "enemy_ai_behavior": "cybernetic",
        "hacking_mechanics": True,
        "stealth_mode": True,
        "time_dilation": True,
    },
    "networking": {
        "multiplayer_enabled": True,
        "max_players": 8,
        "server_ip": "127.0.0.1",
        "server_port": 8080,
        "encryption_level": "AES-256",
    },
    "logging": {
        "log_level": "DEBUG",
        "log_to_file": True,
        "log_file": "logs/game_debug.log",
    },
}