version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    ports:
      - "6379:6379"